name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-rust:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            lib_name: libsketchboot_native.so
          - os: windows-latest
            lib_name: sketchboot_native.dll
          - os: macos-latest
            lib_name: libsketchboot_native.dylib
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build Rust
        working-directory: sketchboot-native
        run: cargo build --release
      - name: Upload Native Artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-libs-${{ matrix.os }}
          path: sketchboot-native/target/release/${{ matrix.lib_name }}

  build-java:
    needs: build-rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22
      
      - name: Download Native Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: native-libs-*
          path: src/main/resources/native
          merge-multiple: true

      - name: Build Java Spring Boot Starter
        run: mvn -B clean package
