name: Publish

on:
  workflow_dispatch:

jobs:
  build-rust:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            lib_name: libsketchboot_native.so
          - os: windows-latest
            lib_name: sketchboot_native.dll
          - os: macos-latest
            lib_name: libsketchboot_native.dylib
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build Rust
        working-directory: sketchboot-native
        run: cargo build --release
      - name: Upload Native Artifact
        uses: actions/upload-artifact@v3
        with:
          name: native-libs
          path: sketchboot-native/target/release/${{ matrix.lib_name }}

  publish-java:
    needs: build-rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 22
          server-id: central
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD

      - name: Download Native Artifacts
        uses: actions/download-artifact@v3
        with:
          name: native-libs
          path: src/main/resources/native

      - name: Import GPG Key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: Publish to Maven Central
        run: |
          mvn -B clean deploy \
          -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
